jaffle_shop:
  target: dev
  outputs:
    dev:
      type: bigquery
      method: service-account
      keyfile: jaffle-dbt-399913-b919530d82c5.json
      project: jaffle-dbt-399913
      dataset: jaffle_shop
      threads: 1
      timeout_seconds: 300
      location: US
      priority: interactive 
